const githubResult = """ 
{
  "total_count": 50482,
  "incomplete_results": false,
  "items": [
    {
      "login": "lucas",
      "id": 1467716,
      "node_id": "MDQ6VXNlcjE0Njc3MTY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1467716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucas",
      "html_url": "https://github.com/lucas",
      "followers_url": "https://api.github.com/users/lucas/followers",
      "following_url": "https://api.github.com/users/lucas/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucas/subscriptions",
      "organizations_url": "https://api.github.com/users/lucas/orgs",
      "repos_url": "https://api.github.com/users/lucas/repos",
      "events_url": "https://api.github.com/users/lucas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "AgtLucas",
      "id": 1909761,
      "node_id": "MDQ6VXNlcjE5MDk3NjE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1909761?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AgtLucas",
      "html_url": "https://github.com/AgtLucas",
      "followers_url": "https://api.github.com/users/AgtLucas/followers",
      "following_url": "https://api.github.com/users/AgtLucas/following{/other_user}",
      "gists_url": "https://api.github.com/users/AgtLucas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AgtLucas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AgtLucas/subscriptions",
      "organizations_url": "https://api.github.com/users/AgtLucas/orgs",
      "repos_url": "https://api.github.com/users/AgtLucas/repos",
      "events_url": "https://api.github.com/users/AgtLucas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AgtLucas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasmontano",
      "id": 7559318,
      "node_id": "MDQ6VXNlcjc1NTkzMTg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/7559318?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasmontano",
      "html_url": "https://github.com/lucasmontano",
      "followers_url": "https://api.github.com/users/lucasmontano/followers",
      "following_url": "https://api.github.com/users/lucasmontano/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasmontano/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasmontano/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasmontano/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasmontano/orgs",
      "repos_url": "https://api.github.com/users/lucasmontano/repos",
      "events_url": "https://api.github.com/users/lucasmontano/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasmontano/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasbento",
      "id": 6207220,
      "node_id": "MDQ6VXNlcjYyMDcyMjA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6207220?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasbento",
      "html_url": "https://github.com/lucasbento",
      "followers_url": "https://api.github.com/users/lucasbento/followers",
      "following_url": "https://api.github.com/users/lucasbento/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasbento/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasbento/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasbento/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasbento/orgs",
      "repos_url": "https://api.github.com/users/lucasbento/repos",
      "events_url": "https://api.github.com/users/lucasbento/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasbento/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasr",
      "id": 730395,
      "node_id": "MDQ6VXNlcjczMDM5NQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/730395?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasr",
      "html_url": "https://github.com/lucasr",
      "followers_url": "https://api.github.com/users/lucasr/followers",
      "following_url": "https://api.github.com/users/lucasr/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasr/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasr/orgs",
      "repos_url": "https://api.github.com/users/lucasr/repos",
      "events_url": "https://api.github.com/users/lucasr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucascaton",
      "id": 86755,
      "node_id": "MDQ6VXNlcjg2NzU1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/86755?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucascaton",
      "html_url": "https://github.com/lucascaton",
      "followers_url": "https://api.github.com/users/lucascaton/followers",
      "following_url": "https://api.github.com/users/lucascaton/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucascaton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucascaton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucascaton/subscriptions",
      "organizations_url": "https://api.github.com/users/lucascaton/orgs",
      "repos_url": "https://api.github.com/users/lucascaton/repos",
      "events_url": "https://api.github.com/users/lucascaton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucascaton/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasfcosta",
      "id": 6868147,
      "node_id": "MDQ6VXNlcjY4NjgxNDc=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6868147?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasfcosta",
      "html_url": "https://github.com/lucasfcosta",
      "followers_url": "https://api.github.com/users/lucasfcosta/followers",
      "following_url": "https://api.github.com/users/lucasfcosta/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasfcosta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasfcosta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasfcosta/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasfcosta/orgs",
      "repos_url": "https://api.github.com/users/lucasfcosta/repos",
      "events_url": "https://api.github.com/users/lucasfcosta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasfcosta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "racerxdl",
      "id": 578310,
      "node_id": "MDQ6VXNlcjU3ODMxMA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/578310?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/racerxdl",
      "html_url": "https://github.com/racerxdl",
      "followers_url": "https://api.github.com/users/racerxdl/followers",
      "following_url": "https://api.github.com/users/racerxdl/following{/other_user}",
      "gists_url": "https://api.github.com/users/racerxdl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/racerxdl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/racerxdl/subscriptions",
      "organizations_url": "https://api.github.com/users/racerxdl/orgs",
      "repos_url": "https://api.github.com/users/racerxdl/repos",
      "events_url": "https://api.github.com/users/racerxdl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/racerxdl/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasmazza",
      "id": 80978,
      "node_id": "MDQ6VXNlcjgwOTc4",
      "avatar_url": "https://avatars0.githubusercontent.com/u/80978?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasmazza",
      "html_url": "https://github.com/lucasmazza",
      "followers_url": "https://api.github.com/users/lucasmazza/followers",
      "following_url": "https://api.github.com/users/lucasmazza/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasmazza/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasmazza/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasmazza/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasmazza/orgs",
      "repos_url": "https://api.github.com/users/lucasmazza/repos",
      "events_url": "https://api.github.com/users/lucasmazza/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasmazza/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucaswadedavis",
      "id": 1842230,
      "node_id": "MDQ6VXNlcjE4NDIyMzA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1842230?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucaswadedavis",
      "html_url": "https://github.com/lucaswadedavis",
      "followers_url": "https://api.github.com/users/lucaswadedavis/followers",
      "following_url": "https://api.github.com/users/lucaswadedavis/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucaswadedavis/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucaswadedavis/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucaswadedavis/subscriptions",
      "organizations_url": "https://api.github.com/users/lucaswadedavis/orgs",
      "repos_url": "https://api.github.com/users/lucaswadedavis/repos",
      "events_url": "https://api.github.com/users/lucaswadedavis/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucaswadedavis/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasb-eyer",
      "id": 1476029,
      "node_id": "MDQ6VXNlcjE0NzYwMjk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1476029?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasb-eyer",
      "html_url": "https://github.com/lucasb-eyer",
      "followers_url": "https://api.github.com/users/lucasb-eyer/followers",
      "following_url": "https://api.github.com/users/lucasb-eyer/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasb-eyer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasb-eyer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasb-eyer/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasb-eyer/orgs",
      "repos_url": "https://api.github.com/users/lucasb-eyer/repos",
      "events_url": "https://api.github.com/users/lucasb-eyer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasb-eyer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Lucas-Developer",
      "id": 24865927,
      "node_id": "MDQ6VXNlcjI0ODY1OTI3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/24865927?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Lucas-Developer",
      "html_url": "https://github.com/Lucas-Developer",
      "followers_url": "https://api.github.com/users/Lucas-Developer/followers",
      "following_url": "https://api.github.com/users/Lucas-Developer/following{/other_user}",
      "gists_url": "https://api.github.com/users/Lucas-Developer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Lucas-Developer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Lucas-Developer/subscriptions",
      "organizations_url": "https://api.github.com/users/Lucas-Developer/orgs",
      "repos_url": "https://api.github.com/users/Lucas-Developer/repos",
      "events_url": "https://api.github.com/users/Lucas-Developer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Lucas-Developer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "LucasBassetti",
      "id": 1014326,
      "node_id": "MDQ6VXNlcjEwMTQzMjY=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1014326?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LucasBassetti",
      "html_url": "https://github.com/LucasBassetti",
      "followers_url": "https://api.github.com/users/LucasBassetti/followers",
      "following_url": "https://api.github.com/users/LucasBassetti/following{/other_user}",
      "gists_url": "https://api.github.com/users/LucasBassetti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LucasBassetti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LucasBassetti/subscriptions",
      "organizations_url": "https://api.github.com/users/LucasBassetti/orgs",
      "repos_url": "https://api.github.com/users/LucasBassetti/repos",
      "events_url": "https://api.github.com/users/LucasBassetti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LucasBassetti/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucas-clemente",
      "id": 918034,
      "node_id": "MDQ6VXNlcjkxODAzNA==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/918034?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucas-clemente",
      "html_url": "https://github.com/lucas-clemente",
      "followers_url": "https://api.github.com/users/lucas-clemente/followers",
      "following_url": "https://api.github.com/users/lucas-clemente/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucas-clemente/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucas-clemente/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucas-clemente/subscriptions",
      "organizations_url": "https://api.github.com/users/lucas-clemente/orgs",
      "repos_url": "https://api.github.com/users/lucas-clemente/repos",
      "events_url": "https://api.github.com/users/lucas-clemente/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucas-clemente/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasconstantino",
      "id": 2688512,
      "node_id": "MDQ6VXNlcjI2ODg1MTI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2688512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasconstantino",
      "html_url": "https://github.com/lucasconstantino",
      "followers_url": "https://api.github.com/users/lucasconstantino/followers",
      "following_url": "https://api.github.com/users/lucasconstantino/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasconstantino/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasconstantino/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasconstantino/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasconstantino/orgs",
      "repos_url": "https://api.github.com/users/lucasconstantino/repos",
      "events_url": "https://api.github.com/users/lucasconstantino/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasconstantino/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucascs",
      "id": 46113,
      "node_id": "MDQ6VXNlcjQ2MTEz",
      "avatar_url": "https://avatars0.githubusercontent.com/u/46113?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucascs",
      "html_url": "https://github.com/lucascs",
      "followers_url": "https://api.github.com/users/lucascs/followers",
      "following_url": "https://api.github.com/users/lucascs/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucascs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucascs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucascs/subscriptions",
      "organizations_url": "https://api.github.com/users/lucascs/orgs",
      "repos_url": "https://api.github.com/users/lucascs/repos",
      "events_url": "https://api.github.com/users/lucascs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucascs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasderraugh",
      "id": 714282,
      "node_id": "MDQ6VXNlcjcxNDI4Mg==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/714282?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasderraugh",
      "html_url": "https://github.com/lucasderraugh",
      "followers_url": "https://api.github.com/users/lucasderraugh/followers",
      "following_url": "https://api.github.com/users/lucasderraugh/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasderraugh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasderraugh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasderraugh/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasderraugh/orgs",
      "repos_url": "https://api.github.com/users/lucasderraugh/repos",
      "events_url": "https://api.github.com/users/lucasderraugh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasderraugh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasmichot",
      "id": 513603,
      "node_id": "MDQ6VXNlcjUxMzYwMw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/513603?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasmichot",
      "html_url": "https://github.com/lucasmichot",
      "followers_url": "https://api.github.com/users/lucasmichot/followers",
      "following_url": "https://api.github.com/users/lucasmichot/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasmichot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasmichot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasmichot/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasmichot/orgs",
      "repos_url": "https://api.github.com/users/lucasmichot/repos",
      "events_url": "https://api.github.com/users/lucasmichot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasmichot/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasjellema",
      "id": 1296324,
      "node_id": "MDQ6VXNlcjEyOTYzMjQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1296324?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasjellema",
      "html_url": "https://github.com/lucasjellema",
      "followers_url": "https://api.github.com/users/lucasjellema/followers",
      "following_url": "https://api.github.com/users/lucasjellema/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasjellema/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasjellema/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasjellema/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasjellema/orgs",
      "repos_url": "https://api.github.com/users/lucasjellema/repos",
      "events_url": "https://api.github.com/users/lucasjellema/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasjellema/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucaschen",
      "id": 2109121,
      "node_id": "MDQ6VXNlcjIxMDkxMjE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2109121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucaschen",
      "html_url": "https://github.com/lucaschen",
      "followers_url": "https://api.github.com/users/lucaschen/followers",
      "following_url": "https://api.github.com/users/lucaschen/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucaschen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucaschen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucaschen/subscriptions",
      "organizations_url": "https://api.github.com/users/lucaschen/orgs",
      "repos_url": "https://api.github.com/users/lucaschen/repos",
      "events_url": "https://api.github.com/users/lucaschen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucaschen/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucaswerkmeister",
      "id": 2346599,
      "node_id": "MDQ6VXNlcjIzNDY1OTk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2346599?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucaswerkmeister",
      "html_url": "https://github.com/lucaswerkmeister",
      "followers_url": "https://api.github.com/users/lucaswerkmeister/followers",
      "following_url": "https://api.github.com/users/lucaswerkmeister/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucaswerkmeister/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucaswerkmeister/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucaswerkmeister/subscriptions",
      "organizations_url": "https://api.github.com/users/lucaswerkmeister/orgs",
      "repos_url": "https://api.github.com/users/lucaswerkmeister/repos",
      "events_url": "https://api.github.com/users/lucaswerkmeister/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucaswerkmeister/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "LucasVanni",
      "id": 26672576,
      "node_id": "MDQ6VXNlcjI2NjcyNTc2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/26672576?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LucasVanni",
      "html_url": "https://github.com/LucasVanni",
      "followers_url": "https://api.github.com/users/LucasVanni/followers",
      "following_url": "https://api.github.com/users/LucasVanni/following{/other_user}",
      "gists_url": "https://api.github.com/users/LucasVanni/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LucasVanni/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LucasVanni/subscriptions",
      "organizations_url": "https://api.github.com/users/LucasVanni/orgs",
      "repos_url": "https://api.github.com/users/LucasVanni/repos",
      "events_url": "https://api.github.com/users/LucasVanni/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LucasVanni/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Lucas170",
      "id": 7984154,
      "node_id": "MDQ6VXNlcjc5ODQxNTQ=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7984154?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Lucas170",
      "html_url": "https://github.com/Lucas170",
      "followers_url": "https://api.github.com/users/Lucas170/followers",
      "following_url": "https://api.github.com/users/Lucas170/following{/other_user}",
      "gists_url": "https://api.github.com/users/Lucas170/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Lucas170/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Lucas170/subscriptions",
      "organizations_url": "https://api.github.com/users/Lucas170/orgs",
      "repos_url": "https://api.github.com/users/Lucas170/repos",
      "events_url": "https://api.github.com/users/Lucas170/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Lucas170/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasfonmiranda",
      "id": 21132056,
      "node_id": "MDQ6VXNlcjIxMTMyMDU2",
      "avatar_url": "https://avatars2.githubusercontent.com/u/21132056?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasfonmiranda",
      "html_url": "https://github.com/lucasfonmiranda",
      "followers_url": "https://api.github.com/users/lucasfonmiranda/followers",
      "following_url": "https://api.github.com/users/lucasfonmiranda/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasfonmiranda/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasfonmiranda/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasfonmiranda/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasfonmiranda/orgs",
      "repos_url": "https://api.github.com/users/lucasfonmiranda/repos",
      "events_url": "https://api.github.com/users/lucasfonmiranda/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasfonmiranda/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasfloriani",
      "id": 36285126,
      "node_id": "MDQ6VXNlcjM2Mjg1MTI2",
      "avatar_url": "https://avatars1.githubusercontent.com/u/36285126?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasfloriani",
      "html_url": "https://github.com/lucasfloriani",
      "followers_url": "https://api.github.com/users/lucasfloriani/followers",
      "following_url": "https://api.github.com/users/lucasfloriani/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasfloriani/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasfloriani/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasfloriani/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasfloriani/orgs",
      "repos_url": "https://api.github.com/users/lucasfloriani/repos",
      "events_url": "https://api.github.com/users/lucasfloriani/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasfloriani/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasmaiaesilva",
      "id": 8356935,
      "node_id": "MDQ6VXNlcjgzNTY5MzU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8356935?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasmaiaesilva",
      "html_url": "https://github.com/lucasmaiaesilva",
      "followers_url": "https://api.github.com/users/lucasmaiaesilva/followers",
      "following_url": "https://api.github.com/users/lucasmaiaesilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasmaiaesilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasmaiaesilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasmaiaesilva/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasmaiaesilva/orgs",
      "repos_url": "https://api.github.com/users/lucasmaiaesilva/repos",
      "events_url": "https://api.github.com/users/lucasmaiaesilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasmaiaesilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasteles",
      "id": 3037609,
      "node_id": "MDQ6VXNlcjMwMzc2MDk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3037609?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasteles",
      "html_url": "https://github.com/lucasteles",
      "followers_url": "https://api.github.com/users/lucasteles/followers",
      "following_url": "https://api.github.com/users/lucasteles/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasteles/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasteles/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasteles/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasteles/orgs",
      "repos_url": "https://api.github.com/users/lucasteles/repos",
      "events_url": "https://api.github.com/users/lucasteles/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasteles/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasjs",
      "id": 14945222,
      "node_id": "MDQ6VXNlcjE0OTQ1MjIy",
      "avatar_url": "https://avatars1.githubusercontent.com/u/14945222?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasjs",
      "html_url": "https://github.com/lucasjs",
      "followers_url": "https://api.github.com/users/lucasjs/followers",
      "following_url": "https://api.github.com/users/lucasjs/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasjs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasjs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasjs/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasjs/orgs",
      "repos_url": "https://api.github.com/users/lucasjs/repos",
      "events_url": "https://api.github.com/users/lucasjs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasjs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "LucasMagnum",
      "id": 1376169,
      "node_id": "MDQ6VXNlcjEzNzYxNjk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1376169?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LucasMagnum",
      "html_url": "https://github.com/LucasMagnum",
      "followers_url": "https://api.github.com/users/LucasMagnum/followers",
      "following_url": "https://api.github.com/users/LucasMagnum/following{/other_user}",
      "gists_url": "https://api.github.com/users/LucasMagnum/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LucasMagnum/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LucasMagnum/subscriptions",
      "organizations_url": "https://api.github.com/users/LucasMagnum/orgs",
      "repos_url": "https://api.github.com/users/LucasMagnum/repos",
      "events_url": "https://api.github.com/users/LucasMagnum/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LucasMagnum/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lucasviola",
      "id": 3988101,
      "node_id": "MDQ6VXNlcjM5ODgxMDE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3988101?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucasviola",
      "html_url": "https://github.com/lucasviola",
      "followers_url": "https://api.github.com/users/lucasviola/followers",
      "following_url": "https://api.github.com/users/lucasviola/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucasviola/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucasviola/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucasviola/subscriptions",
      "organizations_url": "https://api.github.com/users/lucasviola/orgs",
      "repos_url": "https://api.github.com/users/lucasviola/repos",
      "events_url": "https://api.github.com/users/lucasviola/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucasviola/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";